### ISSUE TITLE
Not working on gnome 44

### ISSUE THREAD

**Issue by iamjomygeorge** [alecdotninja/no-titlebar-when-maximized#10] opened 2023-04-24 23:44 UTC
I recently upgraded to Fedora 38, which includes the latest version of the Gnome desktop environment (Gnome 44). However, I have encountered an issue where some of the extensions that I had previously installed are no longer working. One such extension is "No Titlebar When Maximized" by @alecdotninja.

I'm not quite sure what to do about this problem, as I'm not very technically inclined. However, I would like to suggest to extension developers that they consider building their extensions in a way that is more resilient to new updates. This could help prevent issues like the one I'm currently experiencing, and improve the overall user experience for those of us who rely on extensions to customize our desktop environments.

**I have tried "Disable version validation". Still not working.**

Here is the screenshot:
![Screenshot from 2023-04-25 05-13-28](https://user-images.githubusercontent.com/83907230/234138731-21d1cdff-ae11-4c08-be13-5b9115662fb2.png)

**Comment by alecdotninja** [comment] 2023-05-23 22:59
> However, I would like to suggest to extension developers that they consider building their extensions in a way that is more resilient to new updates.

The manifest for extensions includes a list of supported GNOME versions. When a new version of GNOME is released, a new version of the extension has to be published with that version in its manifest. In this case, @antoniomarcelo12 verified that it is working and updated the manifest in #11 (which is now released).

I am on Arch so I usually notice when a new version is released and make this update, but sometimes Fedora gets the new GNOME version first. In any case, it seems to be a manual verification process by design. I'm sorry this means the extension stops working for new updates sometimes.

Since a version supporting GNOME 44 is already released, I am going to close this for now. If someone knows a way to avoid this problem, please let me know.

**Closed by alecdotninja** 2023-05-23 22:59 UTC
